[package]
name = "gui-app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
dialoguer = "0.10.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

